// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PingPongManagmantSystem.DataAccess.Constans;

#nullable disable

namespace PingPongManagmantSystem.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230312074752_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("PingPongManagmantSystem.Domain.Entities.BarCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("BarCounts");
                });

            modelBuilder.Entity("PingPongManagmantSystem.Domain.Entities.BarProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ArrivalPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SalePrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("BarProducts");
                });

            modelBuilder.Entity("PingPongManagmantSystem.Domain.Entities.BarStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BarSum")
                        .HasColumnType("REAL");

                    b.Property<double>("Card")
                        .HasColumnType("REAL");

                    b.Property<double>("Cash")
                        .HasColumnType("REAL");

                    b.Property<string>("Check")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("NumberOfSaleBar")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("BarStatistics");
                });

            modelBuilder.Entity("PingPongManagmantSystem.Domain.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("TimeLimit")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("PingPongManagmantSystem.Domain.Entities.Cassa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BarProductPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Check")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SumPrice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TablePrice")
                        .HasColumnType("REAL");

                    b.Property<string>("TypeOfPrice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cassas");
                });

            modelBuilder.Entity("PingPongManagmantSystem.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Percent")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PingPongManagmantSystem.Domain.Entities.DesktopCassa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountBook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Bar")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BarSum")
                        .HasColumnType("REAL");

                    b.Property<bool>("Calc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Label")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pause")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Play")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PlayTime")
                        .HasColumnType("REAL");

                    b.Property<int>("StolNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Stop")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TimeAccount")
                        .HasColumnType("REAL");

                    b.Property<bool>("Transfer")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TransferSum")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DesktopCassas");
                });

            modelBuilder.Entity("PingPongManagmantSystem.Domain.Entities.EmpolyeeStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BarSum")
                        .HasColumnType("REAL");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SportSum")
                        .HasColumnType("REAL");

                    b.Property<double>("TableSum")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ViCardToSell")
                        .HasColumnType("REAL");

                    b.Property<double>("VipCardSum")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("EmpolyeeStatistics");
                });

            modelBuilder.Entity("PingPongManagmantSystem.Domain.Entities.PingPongTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PriceCheap")
                        .HasColumnType("REAL");

                    b.Property<double>("PriceExpensive")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("PingPongTables");
                });

            modelBuilder.Entity("PingPongManagmantSystem.Domain.Entities.SportCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SportCounts");
                });

            modelBuilder.Entity("PingPongManagmantSystem.Domain.Entities.SportProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ArrivalPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SalePrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SportProducts");
                });

            modelBuilder.Entity("PingPongManagmantSystem.Domain.Entities.SportStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Card")
                        .HasColumnType("REAL");

                    b.Property<double>("Cash")
                        .HasColumnType("REAL");

                    b.Property<string>("Check")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("NumberOfSaleSport")
                        .HasColumnType("REAL");

                    b.Property<double>("SportSum")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SportStatistics");
                });

            modelBuilder.Entity("PingPongManagmantSystem.Domain.Entities.TableStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Card")
                        .HasColumnType("REAL");

                    b.Property<double>("Cash")
                        .HasColumnType("REAL");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TableSum")
                        .HasColumnType("REAL");

                    b.Property<double>("VipCard")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TableStatistics");
                });

            modelBuilder.Entity("PingPongManagmantSystem.Domain.Entities.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("TimeCheapFrom")
                        .HasColumnType("REAL");

                    b.Property<double>("TimeCheapUpTo")
                        .HasColumnType("REAL");

                    b.Property<double>("TimeExpensiveFrom")
                        .HasColumnType("REAL");

                    b.Property<double>("TimeExpensiveUpTo")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("PingPongManagmantSystem.Domain.Entities.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("PingPongManagmantSystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHasher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
